# Copyright (C) 2026 Sam Dornan
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.


name: Build and Push Pi Monitor

on:
  workflow_dispatch: # Manual trigger via GitHub Actions

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Generate Source SBOM
        run: |
          curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x $RUNNER_TEMP/sbom-tool
          
          # Adjusted paths to scan the root directory instead of ./brownout
          $RUNNER_TEMP/sbom-tool generate -b ./servicehealth -bc ./servicehealth -pn PiProdBase -pv 1.0.0 -ps S-Dornan -nsb https://github.com/${{ github.repository }}/sbom/pi-push-monitor-base -V Verbose

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v7
        with:
          name: source-sbom-manifest
          path: ./servicehealth/_manifest
        
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository_owner }}/pi-push-monitor-base
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4.5.2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./servicehealth # Tells Docker to look inside the servicehealth folder for the Dockerfile
          platforms: linux/arm64 # Or linux/arm/v7 if you are on 32-bit Pi OS
          push: true
          sbom: true
          provenance: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}